---
framework: jest
blocklist:
  - "src/cheerio.spec.ts##cheerio##cheerio('') should be empty##"
  - "src/cheerio.spec.ts##cheerio##cheerio(selector) with no context or root should be empty##"
postMerge:
  pattern:
    - './src/**/*.spec.ts'
preMerge:
  pattern:
    - './src/**/*.spec.ts'
preRun:
  - npm ci
postRun:
  - node --version
version: 2.0
